analyzer:
  errors:
    avoid_bool_literals_in_conditional_expressions: ignore
    lines_longer_than_80_chars: ignore ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false